### ISSUE TITLE
docker-compose deploy step by step

### ISSUE THREAD

**Issue by jujes** [hooram/ownphotos-frontend#8]
Hi, regarding deploy ownphotos using docker, what is the success way?

+  I need download both front and back repo??
+  After downloads just docker-compose up -d??
+ After deploy, into the backend  docker exec -it  bash <djangoTag>
++ python manage.py migrate
++ python manage.py migrate --run-syncdb
++ python manage.py createsuperuser # will prompt for username and password. use admin/password

thanks in advance,

**Comment by GrumpyMeow** [comment]
The instructions of hooram are quite good, but still had to do some modifications.  Mostly because i run docker on a headless Ubuntu server. Hopefully this write-up will also help others...

# Create a local Docker registry
1. Run: docker run -d -p 5000:5000 --restart=always --name registry registry:2

# Git source-code from github repos
1. Change to a working directory 
1. Git the frontend: git clone https://github.com/hooram/ownphotos-frontend.git
1. Git the backend: git clone https://github.com/hooram/ownphotos-backend.git

# Build docker image ownphotos-backend
1. Change working directory to backend: cd ownphotos-backend
1. Run: docker build -t ownphotos-backend .
1. Wait...
1. Publish image: docker push ownphotos-backend

# Modify frontend package.json to skip Interactive Installer of semantic-ui
1. Change working directory to backend: cd ownphotos-frontend
1. vi package.json
1. remove the line with "semantic-ui"

# Build docker image ownphotos-frontend
1. Change working directory to frontend: cd ownphotos-frontend
1. Run: docker build -t ownphotos-frontend .
1. Wait...
1. Publish image: docker push ownphotos-frontend

# Install docker-compose
1. Install "docker-compose" following the description at: https://docs.docker.com/compose/install/

# Add static hostnames to your router for "memcached" and "database"

# Modify compose file to bind to other network interface (mine has name: macvlan0)
1. Change working directory to frontend: cd ownphotos-frontend
1. Run: vi docker-compose.yml
1. Add at the end of the file (!without inital identation!):
```
networks:
   default:
       external:
          name: macvlan0
```

# Create containers using docker-compose
1. Change working directory to frontend: cd ownphotos-frontend
1. Run: docker-compose up

# Modify frontend to backend connection (if needed)
1. Open a console to the frontend container
2. Run: apt update
3. Run: apt install nano
4. Run: nano /usr/src/app/src/api_client/apiClient.js
5. Replace twice "http://localhost:8000" with a correct value ("http://<machinename>:8000")

# Backend install
1. Open a console to the backend container
2. Run: apt update
3. Run: 
```
	sudo apt install python-pip
	pip install virtualenv
	cd && mkdir venvs
	virtualenv -p /usr/bin/python3 ~/venvs/ownphotos 
	source ~/venvs/ownphotos/bin/activate
```
4. Run: apt install cmake
5. Run: apt install git
5. Run:
```
	git clone https://github.com/davisking/dlib.git
	cd dlib
	mkdir build; cd build; cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1;
	cmake --build .
	cd ..
	python3 setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA
```
6. Run:
```
	cd
	git clone https://github.com/hooram/ownphotos-backend.git
	cd ownphotos-backend
	pip install -r requirements.txt
```

#  Get a mapzen api key
1. Open: https://mapzen.com/
2. Create your personal mapzen api key
3. Run on console backend: export MAPZEN_API_KEY=mapzen-xxxx
4. Run: python manage.py startserver

todo: allowed hosts should probably be modified

tips at hooram:
* add MAPZEN_API_KEY as environment variable to the backend dockerfile
* add BACKEND_HOST as environment variable to the frontend dockerfile and code




... to be continued ...

**Comment by guysoft** [comment]
Not up to date anymore, there is no localhost in api_client/apiClient.js: https://github.com/hooram/ownphotos-frontend/blob/dev/src/api_client/apiClient.js

**Comment by guysoft** [comment]
Ok got it finally! I also made a PR https://github.com/hooram/ownphotos-frontend/pull/31

Basically you can do this now:
```
wget https://raw.githubusercontent.com/guysoft/ownphotos-frontend/dev/docker-compose.yml
sudo docker-compose up -d
```

Thats it, you have ownphotos ruining at http://localhost:3000
(These commands already work now and you can test this)

**Comment by 2nutz4u** [comment]
> 
> 
> Ok got it finally! I also made a PR #31
> 
> Basically you can do this now:
> 
> ```
> wget https://raw.githubusercontent.com/guysoft/ownphotos-frontend/dev/docker-compose.yml
> sudo docker-compose up -d
> ```
> 
> Thats it, you have ownphotos ruining at http://localhost:3000
> (These commands already work now and you can test this)

I ran the yml using  the file. I only changed the mapbox key. I got "No connection to backend server". What could I be doing wrong?

**Comment by guysoft** [comment]
1. give it a little time, the backend takes time to load.
2. What does http://localhost:300/api show? Should see the backend there.
(If you edited the file please share).

**Comment by 2nutz4u** [comment]
> 1. give it a little time, the backend takes time to load. 2. What does http://localhost:300/api show? Should see the backend there. (If you edited the file please share).

Error from http://localhost:300/api. The site can't be reached but when I use http://localhost:3000/api page not found 404 
Request Method: | GET
http://backend/api

Like I said before only change I made to the file was add the madbox api key but just in case..

version: '2'

services:

  proxy:
    image: guysoft/ownphotos-proxy
    tty: true
    container_name: ownphotos-proxy
    restart: always
    links:
      - "backend:backend"
      - "frontend:frontend"
    ports:
      - "3000:80"

  ownphotos-db:
    image: postgres
    container_name: ownphotos-db
    restart: always
    environment:
    # This db password is internal, you can change it if you want, but also change it in ownphotos-backend container
      - POSTGRES_PASSWORD=AaAa1234
      - POSTGRES_DB=ownphotos
    volumes:
      - ownphotos-data:/var/lib/postgresql/data

  frontend:
    container_name: ownphotos-frontend
    image: guysoft/ownphotos-frontend:dev
    # For development uncomment this and comment the image name above
    #build: .
    tty: true
    environment:
       # This is the path to the backend host public facing. if your website is ownphotos.org then this should be "ownphotos.org".
       # Default here is assuming you are running on localhost on port 3000 as given in ownphotos-proxy service
       - BACKEND_HOST=localhost:3000
    links:
      - "backend:backend"

  backend:
    image: hooram/ownphotos:dev
    container_name: ownphotos-backend
    volumes:
      # Your photos go here
      - $HOME/Pictures/:/data
      - media:/code/media
    environment:
      - SECRET_KEY=change_meme
      # This is backend host from within the service, you dont need to change this
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_USERNAME=admin
      # Change your admin password!
      - ADMIN_PASSWORD=admin
      - DEBUG=true
      - DB_BACKEND=postgresql
      - DB_NAME=ownphotos
      - DB_USER=postgres
      # This db password is internal, you can change it if you want, but also change it in ownphotos-db container
      - DB_PASS=AaAa1234
      - DB_HOST=ownphotos-db
      - DB_PORT=5432
      - REDIS_HOST=ownphotos-redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY= MY_API_KEY_HERE
    links:
      - "ownphotos-db:ownphotos-db"
      - "ownphotos-redis:ownphotos-redis"

  ownphotos-redis:
    image: redis
    container_name: ownphotos-redis

volumes:
  ownphotos-data:
  media:

**Comment by 2nutz4u** [comment]
docker ps outpout:
EATED             STATUS              PORTS                        NAMES
c808f9260abf        guysoft/ownphotos-proxy          "nginx -g 'daemon of…"   2                                                                                         minutes ago       Up About a minute   0.0.0.0:3000->80/tcp         ownphotos-pro                                                                                        xy
f10edfc4aa57        guysoft/ownphotos-frontend:dev   "./run.sh"               2                                                                                         minutes ago       Up 2 minutes        3000/tcp                     ownphotos-fro                                                                                        ntend
54fd214d97cb        hooram/ownphotos:dev             "/bin/sh -c ./entryp…"   2                                                                                         minutes ago       Up 2 minutes        80/tcp, 3000/tcp, 5000/tcp   ownphotos-bac                                                                                        kend
d15fec6c501d        postgres                         "docker-entrypoint.s…"   12                                                                                         hours ago        Up 2 minutes        5432/tcp                     ownphotos-db
3b6d79a15b03        redis                            "docker-entrypoint.s…"   12                                                                                         hours ago        Up 2 minutes        6379/tcp                     ownphotos-red

**Comment by guysoft** [comment]
I am not sure what is going on there. Can you try recreating the whole environment?

```
docker-compose stop
docker-compose rm -f
docker volume prune
docker-compose pull
docker-compose up -d
```

**Comment by 2nutz4u** [comment]
No go. Same issue. :(

**Comment by guysoft** [comment]
Ok, I am going to be a little more pedantic, so I can understand where what you are doing is different from what I am doing, so we can figure out what is wrong.

First, I can't really see the indentation from your pastings. And there is strange stuff, for exapmle you pasted ``fro ntend`` with a space in the middle.

Can you please post:
1. your ``docker-compose.yml`` with markdown ``insert code`` tags. see: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code . Alternately attach the file.
2. your pasted output using the same method.

**Comment by 2nutz4u** [comment]
Hopefully the format is correct.

`````docker-compose.yml
version: '2'

services:

  proxy:
    image: guysoft/ownphotos-proxy
    tty: true
    container_name: ownphotos-proxy
    restart: always
    links:
      - "backend:backend"
      - "frontend:frontend"
    ports:
      - "3000:80"
      
  ownphotos-db:
    image: postgres
    container_name: ownphotos-db
    restart: always
    environment:
    # This db password is internal, you can change it if you want, but also change it in ownphotos-backend container
      - POSTGRES_PASSWORD=AaAa1234
      - POSTGRES_DB=ownphotos
    volumes:
      - ownphotos-data:/var/lib/postgresql/data

  frontend:
    container_name: ownphotos-frontend
    image: guysoft/ownphotos-frontend:dev
    # For development uncomment this and comment the image name above
    #build: .
    tty: true
    environment:
       # This is the path to the backend host public facing. if your website is ownphotos.org then this should be "ownphotos.org".
       # Default here is assuming you are running on localhost on port 3000 as given in ownphotos-proxy service
       - BACKEND_HOST=localhost:3000
    links:
      - "backend:backend"

  backend:
    image: hooram/ownphotos:dev
    container_name: ownphotos-backend
    volumes:
      # Your photos go here
      - $HOME/Pictures/:/data
      - media:/code/media
    environment:
      - SECRET_KEY=12345678901234567890
      # This is backend host from within the service, you dont need to change this
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_USERNAME=admin
      # Change your admin password!
      - ADMIN_PASSWORD=admin
      - DEBUG=true
      - DB_BACKEND=postgresql
      - DB_NAME=ownphotos
      - DB_USER=postgres
      # This db password is internal, you can change it if you want, but also change it in ownphotos-db container
      - DB_PASS=AaAa1234
      - DB_HOST=ownphotos-db
      - DB_PORT=5432
      - REDIS_HOST=ownphotos-redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=sk.eyJ1IjoiMm51dHo0dSIsImEiOiJjanB5dGp4NDlsZ2hmbnBkMzhqIn0.LwjhMru8-cDuwpTjTsAmKA
    links:
      - "ownphotos-db:ownphotos-db"
      - "ownphotos-redis:ownphotos-redis"
  
  ownphotos-redis:
    image: redis
    container_name: ownphotos-redis

volumes:
  ownphotos-data:
  media:
`````
Below is docker Ps out put
````Docker PS
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                  NAMES
4454363cafb7        guysoft/ownphotos-proxy          "nginx -g 'daemon of…"   9 minutes ago       Up 9 minutes        0.0.0.0:3000->80/tcp   ownphotos-proxy
89651cd663c7        guysoft/ownphotos-frontend:dev   "./run.sh"               9 minutes ago       Up 9 minutes        3000/tcp               ownphotos-frontend
bd9107f7b5d8        hooram/ownphotos:dev             "/bin/sh -c ./entryp…"   9 minutes ago       Up 9 minutes        80/tcp, 5000/tcp       ownphotos-backend
5222438794eb        postgres                         "docker-entrypoint.s…"   9 minutes ago       Up 9 minutes        5432/tcp               ownphotos-db
16ed7e7b56e4        redis                            "docker-entrypoint.s…"   9 minutes ago       Up 9 minutes        6379/tcp               ownphotos-redis
''''
